{
 "title": "NiFi PrometheusReportingTask Dashboard",
 "description": "A complete dashboard for all metrics exposed using PrometheusReportingTask",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nifi_jvm_uptime" }
     ]
    },
    {
     "title": "JVM Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
     "targets": [
      { "expr": "nifi_jvm_heap_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
     "targets": [
      { "expr": "nifi_jvm_heap_used", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Deamon Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
     "targets": [
      { "expr": "nifi_jvm_daemon_thread_count", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Heap Non Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
     "targets": [
      { "expr": "nifi_jvm_heap_non_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM GC Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
     "targets": [
      { "expr": "nifi_jvm_gc_time", "legendFormat": "{{gc_name}}" }
     ]
    },
    {
     "title": "JVM GC Runs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
     "targets": [
      { "expr": "nifi_jvm_gc_runs", "legendFormat": " {{gc_name}}" }
     ]
    },
    {
     "title": "JVM File Descriptor Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 150 },
     "targets": [
      { "expr": "nifi_jvm_file_descriptor_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
     "targets": [
      { "expr": "nifi_jvm_thread_count", "legendFormat": " " }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Lineage Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_average_lineage_duration",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terminated Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_threads_terminated",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_threads_active",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlowFiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received FlowFiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_received",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Transferred FlowFiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_transferred",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent FlowFiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_sent",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Removed FlowFiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_removed",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Items",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_items_input",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Output Items",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_items_output",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Queued Items",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_amount_items_queued",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Contents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Input Content",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "nifi_size_content_input_total",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Total Output Content",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "nifi_size_content_output_total",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Total Queued Content",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "nifi_size_content_queued_total",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  { "title": "Backpressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Backpressure Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_backpressure_bytes_threshold",
     "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
    }
   ]
  },
  {
   "title": "Backpressure Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_backpressure_object_threshold",
     "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
    }
   ]
  },
  {
   "title": "Backpressure Enabled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_backpressure_enabled",
     "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Transferred Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_amount_bytes_transferred",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_amount_bytes_received",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Written Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_amount_bytes_written",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_amount_bytes_sent",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_amount_bytes_read",
     "legendFormat": "{{component_type}} {{component_name}}"
    }
   ]
  }
 ]
}