global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:

  - job_name: 'nifi'
    scheme: https
    metrics_path: /nifi-api/flow/metrics/prometheus
    static_configs:
      - targets: ['nifi:8443']
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/secrets/nifi_token.txt
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'kafka-staleness'
    static_configs:
      - targets: ['kafka-staleness-exporter:9309']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:9249']
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['taskmanager:9250']
