{
 "title": "NIFi Connections And Processors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Aggregate queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate queues > 100000",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk(20, nifi_amount_items_queued) > 100000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate 1000 < queue < 100000",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "topk(20, nifi_amount_items_queued) > 10000 < 100000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate 1000 < queues < 10000",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "topk(20, 1000 < nifi_amount_items_queued < 10000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate queue < 1000",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "topk(20, nifi_amount_items_queued) < 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregate input/output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate inputs ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 299 },
     "targets": [
      {
       "expr": "topk(20, nifi_amount_items_input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate input increase per 1 min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 308 },
     "targets": [
      {
       "expr": "topk(20,increase(nifi_amount_items_input{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate outpus",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 317 },
     "targets": [
      {
       "expr": "topk(20, nifi_amount_items_output)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate Rate output",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 326 },
     "targets": [
      {
       "expr": "topk(20,increase(nifi_amount_items_output{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Data ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Nobitex raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"NOBITEX\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nobitex queues",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"805ea3a7-e61d-30e7-1c33-8f52f121fb6b\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitpin raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"BITPIN\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitpin queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "topk(50, nifi_amount_items_queued{parent_id=\"efd6fe2a-b591-3217-8806-d81e78e2b45d\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallex raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"WALLEX\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallex queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"be11f60b-31ba-3766-6691-401d4fa85c0c\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ramzinex raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"RAMZINEX\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ramzinex queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"5567d6bc-03c2-3837-d040-5a51c38d9a5a\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitget raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"BITGET\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitget queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"a8aeb51e-8d65-38e4-658d-d25f1dbd4995\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bybit raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"BYBIT\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bybite queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"3e802203-2e27-37e5-c9f1-ba8459a3b083\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ompfinex raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"OMPFINEX\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ompfinex queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"9b6b0d99-c511-393a-3a7b-9f9c06f0d838\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Okx raw orderbook last 1m ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "increase(nifi_amount_items_output{component_name=\"OKX\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Okx queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "topk(50,nifi_amount_items_queued{parent_id=\"c750cb31-4d4e-36ce-4091-6acea8b533b2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Normalization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Delivery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "queue/input delivery - UpdateAttribute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 633 },
     "targets": [
      {
       "expr": "nifi_amount_items_queued{component_id=\"fbce0840-d208-3304-49f6-66151b6689fe\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "queue/UpdateAttribute - PublishKafka",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 641 },
     "targets": [
      {
       "expr": "nifi_amount_items_queued{component_id=\"14e9080f-d47e-36ed-3807-f1823c14c7ff\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}